### ISSUE TITLE
Ch1 Q14

### ISSUE THREAD

**Issue by JoeZiminski** [fifthist/Introduction-To-Probability-Blitzstein-Solutions#2]
Dear fifthist,

Firstly I'd just like to say thanks for taking the time to upload your answers to this repo. I have been working through this book also and was really desperate to check my answers / see the solution when I could not figure it out so I really appreciate this resource and the insight gained for from your answers.

For Ch1 Q14 I got a different answer, based on the number of ways to count the possible combinations of pizzas. In the question it says 'any combination of 8 possible toppings' which I took to mean there are 8 choices for toppings and we can have any combination (rather than 8 possible toppings total). As such I calculated the possible number of pizzas as:

(in matlab code):
```4 * nchoosek(8, 0) + nchoosek(8, 1) + nchoosek(8, 2) + nchoosek(8, 3) + nchoosek(8, 4) + nchoosek(8, 5) + nchoosek(8, 6) + nchoosek(8, 7) + nchoosek(8,8)``` = 1024

From this I used the Bose-Einstein coefficient to get a final answer of nchoosek(1023, 2). Please let me know what you think!

Best,
Joe

**Comment by fifthist** [comment]
Hi Joe. Glad you are finding the repo helpful!

I think you are right in your interpretation of 8 possible toppings.
Certainly makes sense to me.

If you wish to open a pull request with your solution, I'm more than happy
to merge it in.

If for some reason you don't want to do that, let me know and I'll push the
update.

Feel free to reach out in case you have further questions.

Cheers!
