### ISSUE TITLE
Error in script run by CI

### ISSUE THREAD

**Issue by rubinduck** [fifthist/Introduction-To-Probability-Blitzstein-Solutions#9]
Seems like current make script have problem causing CI to fail (#8)
![изображение](https://user-images.githubusercontent.com/67712599/115949275-9be26d00-a4dc-11eb-86e9-a8d2b32e25bc.png)
Maybe it somehow related to make4ht version, but I couldn't check it because line logging version shows literal string 'make4ht --version' instead of version. 
![изображение](https://user-images.githubusercontent.com/67712599/115949521-722a4580-a4de-11eb-9fe3-a90bcf07393f.png)
You may want to change command to 'make4ht --version' without echo.

**Comment by fifthist** [comment]
This has been on my radar for a while now. Will address this over the weekend.

**Comment by fifthist** [comment]
Fixed. Closing the issue.
